/*******************************************************************************
* Copyright (c) 2022 Red Hat Inc. and others.
* All rights reserved. This program and the accompanying materials
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v20.html
*
* SPDX-License-Identifier: EPL-2.0
*
* Contributors:
*     Red Hat Inc. - initial API and implementation
*******************************************************************************/
package org.eclipse.lemminx.extensions.xerces;

import java.text.MessageFormat;
import java.util.Locale;
import java.util.MissingResourceException;

import org.apache.xerces.util.MessageFormatter;
import org.eclipse.lemminx.extensions.contentmodel.participants.RelaxNGErrorCode;

/**
 * Formats messages generated by the RelaxNG schema formatter.
 *
 * @author datho7561
 */
public class RelaxNGMessageFormatter implements MessageFormatter {

	public static final String RELAXNG_DOMAIN = "https://relaxng.org";

	private static final String INVALID_RELAXNG_MESSAGE_TEMPLATE = "The RelaxNG schema {0} is invalid: {1}";

	@Override
	public String formatMessage(Locale locale, String key, Object[] arguments) throws MissingResourceException {

		RelaxNGErrorCode code = RelaxNGErrorCode.get(key);
		if (code == null) {
			return null;
		}
		switch (code) {
			case InvalidRelaxNG: {
				return MessageFormat.format(INVALID_RELAXNG_MESSAGE_TEMPLATE, arguments);
			}
			default:
				return null;
		}
	}

}
